export { default as BoardView } from './views/BoardView.vue'
export { default as BoardCanvas } from './components/canvas/BoardCanvas.vue'
export { default as BoardToolbar } from './components/toolbar/BoardToolbar.vue'
export { default as LayersPanel } from './components/layers/LayersPanel.vue'
export { default as HistoryPanel } from './components/history/HistoryPanel.vue'
export { default as PropertiesPanel } from './components/properties/PropertiesPanel.vue'
export { default as TemplateGallery } from './components/templates/TemplateGallery.vue'
export { default as ExportModal } from './components/export/ExportModal.vue'
export { default as VideoOverlay } from './components/video/VideoOverlay.vue'
export { default as MiniMap } from './components/shared/MiniMap.vue'
export { useBoard } from './composables/useBoard'
