# Generated by Django 5.2.9 on 2025-12-12 19:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoloSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Untitled', max_length=255)),
                ('state', models.JSONField(default=dict)),
                ('page_count', models.PositiveIntegerField(default=1)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solo_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'solo_session',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SoloExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('format', models.CharField(choices=[('png', 'PNG Image'), ('pdf', 'PDF Document'), ('json', 'JSON Data')], max_length=10)),
                ('file_url', models.URLField()),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='solo.solosession')),
            ],
            options={
                'db_table': 'solo_export',
                'ordering': ['-created_at'],
            },
        ),
    ]
