# Generated by Cascade on 2025-12-17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solo', '0006_v029_diff_rev_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoloUserStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_bytes', models.BigIntegerField(default=0)),
                ('quota_bytes', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solo_storage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'solo_user_storage',
            },
        ),
    ]
