# Generated by Django 5.2.9 on 2025-12-20 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solo', '0007_solo_user_storage'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='solosession',
            name='solo_session_user_updated_idx',
        ),
        migrations.RemoveIndex(
            model_name='solosession',
            name='solo_session_id_rev_idx',
        ),
        migrations.RenameIndex(
            model_name='soloexport',
            new_name='solo_export_session_7dee1c_idx',
            old_name='solo_export_session_status_idx',
        ),
        migrations.RenameIndex(
            model_name='soloexport',
            new_name='solo_export_user_id_fe074b_idx',
            old_name='solo_export_user_created_idx',
        ),
    ]
