/**
 * cloneIdentity — derive new EO identity from source (clone / fork / duplicate).
 *
 * SSOT §2.2 ID-INV-5:
 *   Cloning an EO: new instance_id, origin_id = source.instance_id,
 *   derived_chain = [...source.derived_chain, source.instance_id].
 *
 * Per ID-INV-3: `origin_id` is immutable (set once at derivation time).
 * Per ID-INV-4: `derived_chain` is append-only.
 *
 * Per colleague review: `derived_chain` must be FROZEN to prevent
 * accidental lineage mutation у downstream callers.
 *
 * Pure function — no I/O, no state. Caller provides `new_instance_id`
 * (typically UUID v4 generated by caller layer).
 */

import type { NormalizedEOIdentity } from '../types/identity'

/**
 * Derive identity for a cloned/forked EO.
 *
 * @param source - normalized identity of the EO being cloned
 * @param newInstanceId - caller-provided unique id for the new instance
 *                        (UUID v4 typically; caller responsibility per
 *                        ID-INV-1 uniqueness invariant)
 * @returns NormalizedEOIdentity of new instance with provenance fields
 *          populated и derived_chain extended (frozen).
 */
export function cloneIdentity(
  source: NormalizedEOIdentity,
  newInstanceId: string,
): NormalizedEOIdentity {
  return {
    instance_id: newInstanceId,
    template_id: source.template_id,
    origin_id: source.instance_id,
    // Append source.instance_id to lineage. Freeze immutable.
    derived_chain: Object.freeze([
      ...source.derived_chain,
      source.instance_id,
    ]),
    // canonical_id preserved (marketplace items keep their canonical id
    // through clones; user can detach by setting null explicitly later).
    canonical_id: source.canonical_id,
  }
}
